version: '3.8'

# Secure override - removes dev_net from workstation entirely
services:
  workstation:
    networks:
      tor_net:
        ipv4_address: 10.152.152.11
    # Remove dev_net completely for security
    environment:
      - DEV_MODE=false  # Disable dev mode features
      - SECURITY_MODE=strict

networks:
  tor_net:
    driver: bridge
    internal: true  # Ensure complete isolation
    ipam:
      driver: default
      config:
        - subnet: 10.152.152.0/24

# If you need dev_net for other containers, keep it separate:
  dev_net:
    driver: bridge
    internal: true  # MUST be internal
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
