version: '3.8'

services:
  workstation:
    networks:
      tor_net:
        ipv4_address: 10.152.152.11
    # dev_net ПОЛНОСТЬЮ УДАЛЕН!

networks:
  tor_net:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.152.152.0/24
